"""add display_order to room_movies

Revision ID: 14506ba92b44
Revises: 8ee4148b85d2
Create Date: 2026-08-17 11:21:55.789535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14506ba92b44'
down_revision: Union[str, Sequence[str], None] = '8ee4148b85d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_movies', sa.Column('display_order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_movies', 'display_order')
    # ### end Alembic commands ###
