"""add user guest fields and room genre

Revision ID: 8ee4148b85d2
Revises: ba76c66d5802
Create Date: 2026-08-17 10:21:13.680921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee4148b85d2'
down_revision: Union[str, Sequence[str], None] = 'ba76c66d5802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('genre', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'is_guest')
    op.drop_column('rooms', 'genre')
    # ### end Alembic commands ###
